services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: ticket_ghar_postgres
    environment:
      POSTGRES_DB: ticket_ghar_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ticket_ghar_dev"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis Cache & Queue
  redis:
    image: redis:6-alpine
    container_name: ticket_ghar_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # pgAdmin (Optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ticket_ghar_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ticketghar.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local 